### PR TITLE
Test procedure for modifying laser alpha values

### PR DESCRIPTION
**Pull request by depasse**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@depasse , resolve merge conflicts. why there is file in data directory?

**Comment by depasse** [comment]
I thought I must preserve the structure of the directory, so have a /data subdirectory.  I didn't know all the files must be at top-level.  How do I delete the data/  ?
________________________________

**Comment by smuzaffar** [comment]
try to do
- git clone https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules.git
- add/update files on top level directory
- git commit
- add your repo: git remote add ....
- push chnage to your repo: git push my-repo master:update-laser-alpha
and then make a PR from your update-laser-alpha branch

**Comment by depasse** [comment]
@smuzaffar :
I have my 4 files in /CMSSW_9_0_0_pre4/CalibCalorimetry-EcalTrivialCondModules 
$ git branch
* master
$ git remote add TestLaserAlpha https://github.com/depasse/TestLaserAlpha
$ git remote -v
TestLaserAlpha  https://github.com/depasse/TestLaserAlpha (fetch)
TestLaserAlpha  https://github.com/depasse/TestLaserAlpha (push)
origin  https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules.git (fetch)
origin  https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules.git (push)
$ git push TestLaserAlpha master:update-laser-alpha  
username, passwd ->
remote: Repository not found.
fatal: repository 'https://github.com/depasse/TestLaserAlpha/' not found..

Could you explain what I have forgotten?  Thanks.

**Comment by smuzaffar** [comment]
you repo is
https://github.com/depasse/CalibCalorimetry-EcalTrivialCondModules.git
and not 
https://github.com/depasse/TestLaserAlpha

**Comment by depasse** [comment]
New git pb : 

$ git remote add UpdateLaserAlpha https://github.com/depasse/CalibCalorimetry-EcalTrivialCondModules.git
$ git push UpdateLaserAlpha master:update-laser-alpha
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/depasse/CalibCalorimetry-EcalTrivialCondModules.git/info/refs

fatal: HTTP request failed

Must I first create locally
$ git checkout update-laser-alpha ?

**Comment by smuzaffar** [comment]
try using  git@github.com:depasse/CalibCalorimetry-EcalTrivialCondModules instead of https://

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules/pull/3

**Pull request closed without merging**
