### PR TITLE
ECAL : New values for Ecal Particle Flow RecHits thresholds

### PR DESCRIPTION
**Pull request by depasse**
Files for EB and EE updated

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
unless there is a corresponding cmssw PR to test with

**Comment by mrodozov** [comment]
please test
(need more recent cms-bot job that will start ib-run-pr-tests job, the old one is gone)

**Comment by depasse** [comment]
News about this extra package PR ?  I don't really understand why there are such tests. 
I have just modified 2 txt files with only data values  inside, no code was changed..

**Comment by mrodozov** [comment]
Code might not change yet I'm sure I can change data files and break a program that's reading this data.
The test looks fine you need alca and orp approval and this gets merged

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
@christopheralanwest, @tocheng, @franzoni, @tlampen, @pohsun can you please sign this?
@depasse , tests are needed in order to make sure the contents of these modified files are not breaking any workflows.

**Comment by christopheralanwest** [comment]
@depasse Could you clarify why these files need to be changed and how the validation was performed? No changes in any reco quantity was generated in the PR comparison tests with these updates. Are these files for local tests only?

**Comment by depasse** [comment]
Before creating this extrapackage, these txt files were included in CMSSW and were often used to produce immediately sqlite files for upload them in cond DB.  But now it is no more possible to keep txt files in CMSSW, if well understood. So it is normal that no changes were generated.

**Comment by depasse** [comment]
Any news on this ?

**Comment by smuzaffar** [comment]
@christopheralanwest, @tocheng, @franzoni, @tlampen, @pohsun can you please look in to this?

**Comment by christopheralanwest** [comment]
+1

I checked that the thresholds are the same as those in the payload `9f22e391bcdcabe1f9f13608961bbed938c8a05c`, which corresponds to `EcalPFRecHitThresholds_2018_v1_mc`

**Pull request merged**
