### PR TITLE
Building CalibCalorimetry EcalTrivialCondModules extra package

### PR DESCRIPTION
**Pull request by depasse**
Move txt files from CMSSW..../CalibCalorimetry/EcalTrivialCondModules/data to extra package

### CODE REVIEW

**Comment by mrodozov** [comment]
assign alca

**Comment by fabiocos** [comment]
@christopheralanwest @tocheng @pohsun this updates addss the data files previously in CMSSW< and allows us to test https://github.com/cms-sw/cmssw/pull/26522

**Comment by fabiocos** [comment]
@tocheng @pohsun this should be ok now

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I would like to close this story in next IB, everything looks consistent now

**Comment by smuzaffar** [comment]
+externals
sure, I am merging it and will create a tag to be included in cmsdist for next IB

**Pull request merged**
